#!/bin/bash

##  Look in my mu4e Todo mail folders, and put the email subjects as headlines in my Orgmode todo list
##  My todo mail folders are all called TodoL (L indicating a Local folder)
##  MvdS, 2020-05-03

MAILDIR="$HOME/.emacs_mail"
ORGFILE="$HOME/.org/Email.org"


function writeLines {
    # Write a todo line:
    # Args:
    #   1) ACCOUNT: mu4e subdir of MAILDIR = email account
    #   2) TAG:     Orgmode tag(s), e.g. :Work:
    #   3) PRIO:    Orgmode priority, e.g. [#C]
    
    ACCOUNT=$1
    TAG=$2
    PRIO=$3
    
    DIR="$MAILDIR/$ACCOUNT/TodoL"
    
    echo "** $ACCOUNT                                                                        $TAG"
    for FILE in `find $DIR -type f`
    do
	FROM=`grep '^From: ' "$FILE" | head -1 | sed -e 's|^From: \(.\)|\U\1|'`
	
	# Remove some utf-8 code:
	SUBJECT=`grep '^Subject: ' "$FILE" | head -1 \
		      | sed -e 's|^Subject: \(.\)|\U\1|' \
			    -e 's|=?utf-8?q?||g' -e 's|?=||g' -e 's|=2C|,|g' -e 's|_| |g' `
	
	# Subject is sometimes on the next line from '^Subject: ':
	if [ "$SUBJECT" == "" ]
	then
	    SUBJECT="Mail from $FROM"
	fi
	
	# Remove Re:, Fwd: from headline:
	HEADLINE=`echo $SUBJECT | sed -e 's| re: | |I' -e 's|^re: ||I' \
		       		      -e 's| fwd: | |I' -e 's|^fwd: ||I'`
			       
	DATE=`grep '^Date: ' "$FILE" | sed -e 's|^Date: ||' | head -1`
	
	# Message ID is sometimess on the next line from '^Message-ID', but always seems to end in '>'.
	# Hence, get the Message-ID line and the next, remove '^Message-ID ... (\n) ... <' and remove '> ... $':
	MSGID=`grep -A1 '^Message-ID' $FILE | sed -n '
		    		      	      	     # if the first line copy the pattern to the hold buffer
						     1h
						     # if not the first line then append the pattern to the hold buffer
						     1!H
						     # if the last line then ...
						     $ {
						             # copy from the hold to the pattern buffer
							     g
                                                             # do the search and replace
                                                             '"s|Message-ID:.*<||"'
                                                             # print
                                                             p
						     }' \
					     `
	MSGID=`echo $MSGID | sed -e 's|>.*$||g'`
	# echo $MSGID
	
	echo "*** TODO $PRIO $ACCOUNT: $HEADLINE"
	echo "  :PROPERTIES:"
	echo "  :ACCOUNT:     $ACCOUNT"
	echo "  :FROM:        $FROM"
	echo "  :DATE:        $DATE"
# 	echo "  :LINK:        file:$FILE"
	echo "  :LINK:        [[mu4e:msgid:$MSGID][$SUBJECT]]"
	echo "  :END:"
    done	    
}


# Count iso todos?
# COUNT=`find $DIR -type f | wc -l`
# echo $COUNT

# Start Orgmode file:
# echo "* Email                                                                   :Email:"  > $ORGFILE
echo "* Email"  > $ORGFILE   # Tag not needed, since category is already specified in file name

# Add todos per email account/subdir:
#           Mu account  Org tag   Prio       Out file
writeLines  "Private"  ":Priv:"  "[#C]"  >>  $ORGFILE
writeLines  "Work"     ":Work:"  "[#C]"  >>  $ORGFILE
